### ISSUE TITLE
DSA / ECDsa tests are failing badly on macOS

### ISSUE THREAD

**Issue by filipnavara** [filipnavara/springburg#16]
```
  Failed GenerateTest("DSA-1024-160.sec","DSA-1024-160.pub",Sha256) [383 ms]
  Error Message:
   Interop+AppleCrypto+AppleCFErrorCryptographicException : The operation couldn’t be completed. (Internal CSSM error error -2147415807 - Internal error #80010901 at SignTransform_block_invoke /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/Security/Security-59754.41.1/OSX/libsecurity_transform/lib/SecSignVerifyTransform.c:326)
  Stack Trace:
     at Interop.AppleCrypto.ExecuteTransform(ReadOnlySpan`1 source, SecKeyTransform transform)
   at Interop.AppleCrypto.GenerateSignature(SafeSecKeyRefHandle privateKey, ReadOnlySpan`1 dataHash)
   at System.Security.Cryptography.DSA.DSAImplementation.DSASecurityTransforms.CreateSignature(Byte[] rgbHash)
   at System.Security.Cryptography.DSA.TryCreateSignatureCore(ReadOnlySpan`1 hash, Span`1 destination, DSASignatureFormat signatureFormat, Int32& bytesWritten)
   at System.Security.Cryptography.DSA.CreateSignatureCore(ReadOnlySpan`1 hash, DSASignatureFormat signatureFormat)
   at System.Security.Cryptography.DSA.CreateSignature(Byte[] rgbHash, DSASignatureFormat signatureFormat)
   at Springburg.Cryptography.OpenPgp.PgpPrivateKey.Sign(Byte[] hash, PgpHashAlgorithm hashAlgorithm) in /Users/filipnavara/Projects/springburg/src/Cryptography/OpenPgp/PgpPrivateKey.cs:line 98
   at Springburg.Cryptography.OpenPgp.PgpSignatureGenerator.Generate() in /Users/filipnavara/Projects/springburg/src/Cryptography/OpenPgp/PgpSignatureGenerator.cs:line 114
   at Springburg.Cryptography.OpenPgp.PgpSignedMessageGenerator.SigningPacketWriter.Dispose() in /Users/filipnavara/Projects/springburg/src/Cryptography/OpenPgp/PgpSignedMessageGenerator.cs:line 62
   at Springburg.Cryptography.OpenPgp.PgpLiteralMessageGenerator.Close() in /Users/filipnavara/Projects/springburg/src/Cryptography/OpenPgp/PgpLiteralMessageGenerator.cs:line 53
   at Springburg.Cryptography.OpenPgp.PgpLiteralMessageGenerator.<GetStream>b__4_0(Stream _) in /Users/filipnavara/Projects/springburg/src/Cryptography/OpenPgp/PgpLiteralMessageGenerator.cs:line 48
   at Springburg.IO.WrappedGeneratorStream.Dispose(Boolean disposing) in /Users/filipnavara/Projects/springburg/src/IO/WrappedGeneratorStream.cs:line 22
   at System.IO.Stream.Close()
   at System.IO.Stream.Dispose()
   at Org.BouncyCastle.Bcpg.OpenPgp.Tests.Dsa2Test.GenerateTest(String privateKeyFile, String publicKeyFile, PgpHashAlgorithm digest) in /Users/filipnavara/Projects/springburg/test/DSA2Test.cs:line 35
  Failed GenerateTest("DSA-1024-160.sec","DSA-1024-160.pub",Sha384) [23 ms]
  Error Message:
   Interop+AppleCrypto+AppleCFErrorCryptographicException : The operation couldn’t be completed. (Internal CSSM error error -2147415807 - Internal error #80010901 at SignTransform_block_invoke /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/Security/Security-59754.41.1/OSX/libsecurity_transform/lib/SecSignVerifyTransform.c:326)
  Stack Trace:
     at Interop.AppleCrypto.ExecuteTransform(ReadOnlySpan`1 source, SecKeyTransform transform)
   at Interop.AppleCrypto.GenerateSignature(SafeSecKeyRefHandle privateKey, ReadOnlySpan`1 dataHash)
   at System.Security.Cryptography.DSA.DSAImplementation.DSASecurityTransforms.CreateSignature(Byte[] rgbHash)
   at System.Security.Cryptography.DSA.TryCreateSignatureCore(ReadOnlySpan`1 hash, Span`1 destination, DSASignatureFormat signatureFormat, Int32& bytesWritten)
   at System.Security.Cryptography.DSA.CreateSignatureCore(ReadOnlySpan`1 hash, DSASignatureFormat signatureFormat)
   at System.Security.Cryptography.DSA.CreateSignature(Byte[] rgbHash, DSASignatureFormat signatureFormat)
   at Springburg.Cryptography.OpenPgp.PgpPrivateKey.Sign(Byte[] hash, PgpHashAlgorithm hashAlgorithm) in /Users/filipnavara/Projects/springburg/src/Cryptography/OpenPgp/PgpPrivateKey.cs:line 98
   at Springburg.Cryptography.OpenPgp.PgpSignatureGenerator.Generate() in /Users/filipnavara/Projects/springburg/src/Cryptography/OpenPgp/PgpSignatureGenerator.cs:line 114
   at Springburg.Cryptography.OpenPgp.PgpSignedMessageGenerator.SigningPacketWriter.Dispose() in /Users/filipnavara/Projects/springburg/src/Cryptography/OpenPgp/PgpSignedMessageGenerator.cs:line 62
   at Springburg.Cryptography.OpenPgp.PgpLiteralMessageGenerator.Close() in /Users/filipnavara/Projects/springburg/src/Cryptography/OpenPgp/PgpLiteralMessageGenerator.cs:line 53
   at Springburg.Cryptography.OpenPgp.PgpLiteralMessageGenerator.<GetStream>b__4_0(Stream _) in /Users/filipnavara/Projects/springburg/src/Cryptography/OpenPgp/PgpLiteralMessageGenerator.cs:line 48
   at Springburg.IO.WrappedGeneratorStream.Dispose(Boolean disposing) in /Users/filipnavara/Projects/springburg/src/IO/WrappedGeneratorStream.cs:line 22
   at System.IO.Stream.Close()
   at System.IO.Stream.Dispose()
   at Org.BouncyCastle.Bcpg.OpenPgp.Tests.Dsa2Test.GenerateTest(String privateKeyFile, String publicKeyFile, PgpHashAlgorithm digest) in /Users/filipnavara/Projects/springburg/test/DSA2Test.cs:line 35
  Failed GenerateTest("DSA-1024-160.sec","DSA-1024-160.pub",Sha512) [12 ms]
  Error Message:
   Interop+AppleCrypto+AppleCFErrorCryptographicException : The operation couldn’t be completed. (Internal CSSM error error -2147415807 - Internal error #80010901 at SignTransform_block_invoke /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/Security/Security-59754.41.1/OSX/libsecurity_transform/lib/SecSignVerifyTransform.c:326)
  Stack Trace:
     at Interop.AppleCrypto.ExecuteTransform(ReadOnlySpan`1 source, SecKeyTransform transform)
   at Interop.AppleCrypto.GenerateSignature(SafeSecKeyRefHandle privateKey, ReadOnlySpan`1 dataHash)
   at System.Security.Cryptography.DSA.DSAImplementation.DSASecurityTransforms.CreateSignature(Byte[] rgbHash)
   at System.Security.Cryptography.DSA.TryCreateSignatureCore(ReadOnlySpan`1 hash, Span`1 destination, DSASignatureFormat signatureFormat, Int32& bytesWritten)
   at System.Security.Cryptography.DSA.CreateSignatureCore(ReadOnlySpan`1 hash, DSASignatureFormat signatureFormat)
   at System.Security.Cryptography.DSA.CreateSignature(Byte[] rgbHash, DSASignatureFormat signatureFormat)
   at Springburg.Cryptography.OpenPgp.PgpPrivateKey.Sign(Byte[] hash, PgpHashAlgorithm hashAlgorithm) in /Users/filipnavara/Projects/springburg/src/Cryptography/OpenPgp/PgpPrivateKey.cs:line 98
   at Springburg.Cryptography.OpenPgp.PgpSignatureGenerator.Generate() in /Users/filipnavara/Projects/springburg/src/Cryptography/OpenPgp/PgpSignatureGenerator.cs:line 114
   at Springburg.Cryptography.OpenPgp.PgpSignedMessageGenerator.SigningPacketWriter.Dispose() in /Users/filipnavara/Projects/springburg/src/Cryptography/OpenPgp/PgpSignedMessageGenerator.cs:line 62
   at Springburg.Cryptography.OpenPgp.PgpLiteralMessageGenerator.Close() in /Users/filipnavara/Projects/springburg/src/Cryptography/OpenPgp/PgpLiteralMessageGenerator.cs:line 53
   at Springburg.Cryptography.OpenPgp.PgpLiteralMessageGenerator.<GetStream>b__4_0(Stream _) in /Users/filipnavara/Projects/springburg/src/Cryptography/OpenPgp/PgpLiteralMessageGenerator.cs:line 48
   at Springburg.IO.WrappedGeneratorStream.Dispose(Boolean disposing) in /Users/filipnavara/Projects/springburg/src/IO/WrappedGeneratorStream.cs:line 22
   at System.IO.Stream.Close()
   at System.IO.Stream.Dispose()
   at Org.BouncyCastle.Bcpg.OpenPgp.Tests.Dsa2Test.GenerateTest(String privateKeyFile, String publicKeyFile, PgpHashAlgorithm digest) in /Users/filipnavara/Projects/springburg/test/DSA2Test.cs:line 35
  Failed SignatureVerifyTest("DSA-1024-160.pub","dsa-1024-256-sign.gpg") [76 ms]
  Error Message:
     Expected: True
  But was:  False

  Stack Trace:
     at Org.BouncyCastle.Bcpg.OpenPgp.Tests.Dsa2Test.SignatureVerifyTest(String publicKeyFile, String sigFile) in /Users/filipnavara/Projects/springburg/test/DSA2Test.cs:line 65

  Failed SignatureVerifyTest("DSA-1024-160.pub","dsa-1024-384-sign.gpg") [7 ms]
  Error Message:
     Expected: True
  But was:  False

  Stack Trace:
     at Org.BouncyCastle.Bcpg.OpenPgp.Tests.Dsa2Test.SignatureVerifyTest(String publicKeyFile, String sigFile) in /Users/filipnavara/Projects/springburg/test/DSA2Test.cs:line 65

  Failed SignatureVerifyTest("DSA-1024-160.pub","dsa-1024-512-sign.gpg") [4 ms]
  Error Message:
     Expected: True
  But was:  False

  Stack Trace:
     at Org.BouncyCastle.Bcpg.OpenPgp.Tests.Dsa2Test.SignatureVerifyTest(String publicKeyFile, String sigFile) in /Users/filipnavara/Projects/springburg/test/DSA2Test.cs:line 65

  Failed SignatureVerifyTest("DSA-3072-256.pub","dsa-3072-256-sign.gpg") [2 ms]
  Error Message:
   System.Security.Cryptography.CryptographicException : Specified key is not a valid size for this algorithm.
  Stack Trace:
     at System.Security.Cryptography.DSA.DSAImplementation.DSASecurityTransforms.ImportParameters(DSAParameters parameters)
   at System.Security.Cryptography.DSA.Create(DSAParameters parameters)
   at Springburg.Cryptography.OpenPgp.PgpPublicKey.GetKey() in /Users/filipnavara/Projects/springburg/src/Cryptography/OpenPgp/PgpPublicKey.cs:line 375
   at Springburg.Cryptography.OpenPgp.PgpPublicKey.Verify(Byte[] hash, Byte[] signature, PgpHashAlgorithm hashAlgorithm) in /Users/filipnavara/Projects/springburg/src/Cryptography/OpenPgp/PgpPublicKey.cs:line 458
   at Springburg.Cryptography.OpenPgp.PgpSignedMessage.Verify(PgpPublicKey publicKey, DateTime& creationTime) in /Users/filipnavara/Projects/springburg/src/Cryptography/OpenPgp/PgpSignedMessage.cs:line 74
   at Springburg.Cryptography.OpenPgp.PgpSignedMessage.Verify(PgpPublicKey publicKey) in /Users/filipnavara/Projects/springburg/src/Cryptography/OpenPgp/PgpSignedMessage.cs:line 61
   at Org.BouncyCastle.Bcpg.OpenPgp.Tests.Dsa2Test.SignatureVerifyTest(String publicKeyFile, String sigFile) in /Users/filipnavara/Projects/springburg/test/DSA2Test.cs:line 65
  Failed KeyPair [4 ms]
  Error Message:
   System.PlatformNotSupportedException : DSA keys can be imported, but new key generation is not supported on this platform.
  Stack Trace:
     at System.Security.Cryptography.DSA.DSAImplementation.DSASecurityTransforms.GetKeys()
   at System.Security.Cryptography.DSA.DSAImplementation.DSASecurityTransforms.ExportParameters(Boolean includePrivateParameters)
   at Springburg.Cryptography.OpenPgp.PgpPublicKey..ctor(AsymmetricAlgorithm pubKey, DateTime time, Boolean isMasterKey) in /Users/filipnavara/Projects/springburg/src/Cryptography/OpenPgp/PgpPublicKey.cs:line 88
   at Springburg.Cryptography.OpenPgp.PgpKeyPair..ctor(AsymmetricAlgorithm keyPair, DateTime time) in /Users/filipnavara/Projects/springburg/src/Cryptography/OpenPgp/PgpKeyPair.cs:line 22
   at Org.BouncyCastle.Bcpg.OpenPgp.Tests.PgpDsaTest.KeyPair() in /Users/filipnavara/Projects/springburg/test/PGPDSATest.cs:line 348
  Failed SxprDecode [342 ms]
  Error Message:
   Interop+AppleCrypto+AppleCommonCryptoCryptographicException : Unknown format in import.
  Stack Trace:
     at Interop.AppleCrypto.ImportEphemeralKey(ReadOnlySpan`1 keyBlob, Boolean hasPrivateKey)
   at System.Security.Cryptography.EccSecurityTransforms.ImportKey(ECParameters parameters)
   at System.Security.Cryptography.EccSecurityTransforms.ImportParameters(ECParameters parameters)
   at System.Security.Cryptography.ECDsa.ECDsaImplementation.ECDsaSecurityTransforms.ImportParameters(ECParameters parameters)
   at System.Security.Cryptography.ECDsa.Create(ECParameters parameters)
   at Springburg.Cryptography.OpenPgp.PgpSecretKey.ExtractPrivateKey(Byte[] rawPassPhrase) in /Users/filipnavara/Projects/springburg/src/Cryptography/OpenPgp/PgpSecretKey.cs:line 379
   at Springburg.Cryptography.OpenPgp.PgpSecretKey.ExtractPrivateKey(String passPhrase) in /Users/filipnavara/Projects/springburg/src/Cryptography/OpenPgp/PgpSecretKey.cs:line 303
   at Org.BouncyCastle.Bcpg.OpenPgp.Tests.PgpECDsaTest.SxprDecode() in /Users/filipnavara/Projects/springburg/test/PgpECDsaTest.cs:line 99
  Failed GenerateSha1Test [460 ms]
  Error Message:
   System.PlatformNotSupportedException : DSA keys can be imported, but new key generation is not supported on this platform.
  Stack Trace:
     at System.Security.Cryptography.DSA.DSAImplementation.DSASecurityTransforms.GetKeys()
   at System.Security.Cryptography.DSA.DSAImplementation.DSASecurityTransforms.ExportParameters(Boolean includePrivateParameters)
   at Springburg.Cryptography.OpenPgp.PgpPublicKey..ctor(AsymmetricAlgorithm pubKey, DateTime time, Boolean isMasterKey) in /Users/filipnavara/Projects/springburg/src/Cryptography/OpenPgp/PgpPublicKey.cs:line 88
   at Springburg.Cryptography.OpenPgp.PgpKeyPair..ctor(AsymmetricAlgorithm keyPair, DateTime time) in /Users/filipnavara/Projects/springburg/src/Cryptography/OpenPgp/PgpKeyPair.cs:line 22
   at Springburg.Cryptography.OpenPgp.PgpKeyRingGenerator..ctor(AsymmetricAlgorithm masterKey, String id, Byte[] rawPassPhrase, DateTime creationTime, Boolean useSha1, PgpSignatureType certificationLevel, PgpSymmetricKeyAlgorithm encAlgorithm, PgpHashAlgorithm hashAlgorithm, PgpSignatureAttributes hashedAttributes, PgpSignatureAttributes unhashedAttributes) in /Users/filipnavara/Projects/springburg/src/Cryptography/OpenPgp/PgpKeyRingGenerator.cs:line 76
   at Springburg.Cryptography.OpenPgp.PgpKeyRingGenerator..ctor(AsymmetricAlgorithm masterKey, String id, String passPhrase, DateTime creationTime, Boolean useSha1, PgpSignatureType certificationLevel, PgpSymmetricKeyAlgorithm encAlgorithm, PgpHashAlgorithm hashAlgorithm, PgpSignatureAttributes hashedAttributes, PgpSignatureAttributes unhashedAttributes) in /Users/filipnavara/Projects/springburg/src/Cryptography/OpenPgp/PgpKeyRingGenerator.cs:line 47
   at Org.BouncyCastle.Bcpg.OpenPgp.Tests.PgpKeyRingTest.GenerateSha1Test() in /Users/filipnavara/Projects/springburg/test/PgpKeyRingTest.cs:line 2085
  Failed GenerateTest [327 ms]
  Error Message:
   System.PlatformNotSupportedException : DSA keys can be imported, but new key generation is not supported on this platform.
  Stack Trace:
     at System.Security.Cryptography.DSA.DSAImplementation.DSASecurityTransforms.GetKeys()
   at System.Security.Cryptography.DSA.DSAImplementation.DSASecurityTransforms.ExportParameters(Boolean includePrivateParameters)
   at Springburg.Cryptography.OpenPgp.PgpPublicKey..ctor(AsymmetricAlgorithm pubKey, DateTime time, Boolean isMasterKey) in /Users/filipnavara/Projects/springburg/src/Cryptography/OpenPgp/PgpPublicKey.cs:line 88
   at Springburg.Cryptography.OpenPgp.PgpKeyPair..ctor(AsymmetricAlgorithm keyPair, DateTime time) in /Users/filipnavara/Projects/springburg/src/Cryptography/OpenPgp/PgpKeyPair.cs:line 22
   at Springburg.Cryptography.OpenPgp.PgpKeyRingGenerator..ctor(AsymmetricAlgorithm masterKey, String id, Byte[] rawPassPhrase, DateTime creationTime, Boolean useSha1, PgpSignatureType certificationLevel, PgpSymmetricKeyAlgorithm encAlgorithm, PgpHashAlgorithm hashAlgorithm, PgpSignatureAttributes hashedAttributes, PgpSignatureAttributes unhashedAttributes) in /Users/filipnavara/Projects/springburg/src/Cryptography/OpenPgp/PgpKeyRingGenerator.cs:line 76
   at Springburg.Cryptography.OpenPgp.PgpKeyRingGenerator..ctor(AsymmetricAlgorithm masterKey, String id, String passPhrase, DateTime creationTime, Boolean useSha1, PgpSignatureType certificationLevel, PgpSymmetricKeyAlgorithm encAlgorithm, PgpHashAlgorithm hashAlgorithm, PgpSignatureAttributes hashedAttributes, PgpSignatureAttributes unhashedAttributes) in /Users/filipnavara/Projects/springburg/src/Cryptography/OpenPgp/PgpKeyRingGenerator.cs:line 47
   at Org.BouncyCastle.Bcpg.OpenPgp.Tests.PgpKeyRingTest.GenerateTest() in /Users/filipnavara/Projects/springburg/test/PgpKeyRingTest.cs:line 2004
  Failed KeyRoundtripRegressionTest [5 ms]
  Error Message:
   System.Security.Cryptography.CryptographicException : Specified key is not a valid size for this algorithm.
  Stack Trace:
     at System.Security.Cryptography.DSA.DSAImplementation.DSASecurityTransforms.ImportParameters(DSAParameters parameters)
   at System.Security.Cryptography.DSA.Create(DSAParameters parameters)
   at Org.BouncyCastle.Bcpg.OpenPgp.Tests.PgpKeyRingTest.KeyRoundtripRegressionTest() in /Users/filipnavara/Projects/springburg/test/PgpKeyRingTest.cs:line 2340
  Failed NestedSignatures [1 ms]
  Error Message:
   System.PlatformNotSupportedException : DSA keys can be imported, but new key generation is not supported on this platform.
  Stack Trace:
     at System.Security.Cryptography.DSA.DSAImplementation.DSASecurityTransforms.GetKeys()
   at System.Security.Cryptography.DSA.DSAImplementation.DSASecurityTransforms.ExportParameters(Boolean includePrivateParameters)
   at Springburg.Cryptography.OpenPgp.PgpPublicKey..ctor(AsymmetricAlgorithm pubKey, DateTime time, Boolean isMasterKey) in /Users/filipnavara/Projects/springburg/src/Cryptography/OpenPgp/PgpPublicKey.cs:line 88
   at Springburg.Cryptography.OpenPgp.PgpKeyPair..ctor(AsymmetricAlgorithm keyPair, DateTime time) in /Users/filipnavara/Projects/springburg/src/Cryptography/OpenPgp/PgpKeyPair.cs:line 22
   at Springburg.Test.PgpArmorTest.NestedSignatures() in /Users/filipnavara/Projects/springburg/test/PgpArmorTest.cs:line 161
Data collector 'Blame' message: All tests finished running, Sequence file will not be generated.
  Failed SimpleSignature [< 1 ms]
  Error Message:
   System.PlatformNotSupportedException : DSA keys can be imported, but new key generation is not supported on this platform.
  Stack Trace:
     at System.Security.Cryptography.DSA.DSAImplementation.DSASecurityTransforms.GetKeys()
   at System.Security.Cryptography.DSA.DSAImplementation.DSASecurityTransforms.ExportParameters(Boolean includePrivateParameters)
   at Springburg.Cryptography.OpenPgp.PgpPublicKey..ctor(AsymmetricAlgorithm pubKey, DateTime time, Boolean isMasterKey) in /Users/filipnavara/Projects/springburg/src/Cryptography/OpenPgp/PgpPublicKey.cs:line 88
   at Springburg.Cryptography.OpenPgp.PgpKeyPair..ctor(AsymmetricAlgorithm keyPair, DateTime time) in /Users/filipnavara/Projects/springburg/src/Cryptography/OpenPgp/PgpKeyPair.cs:line 22
   at Springburg.Test.PgpArmorTest.SimpleSignature() in /Users/filipnavara/Projects/springburg/test/PgpArmorTest.cs:line 136
  Failed CompressedDataInSignature [< 1 ms]
  Error Message:
   System.PlatformNotSupportedException : DSA keys can be imported, but new key generation is not supported on this platform.
  Stack Trace:
     at System.Security.Cryptography.DSA.DSAImplementation.DSASecurityTransforms.GetKeys()
   at System.Security.Cryptography.DSA.DSAImplementation.DSASecurityTransforms.ExportParameters(Boolean includePrivateParameters)
   at Springburg.Cryptography.OpenPgp.PgpPublicKey..ctor(AsymmetricAlgorithm pubKey, DateTime time, Boolean isMasterKey) in /Users/filipnavara/Projects/springburg/src/Cryptography/OpenPgp/PgpPublicKey.cs:line 88
   at Springburg.Cryptography.OpenPgp.PgpKeyPair..ctor(AsymmetricAlgorithm keyPair, DateTime time) in /Users/filipnavara/Projects/springburg/src/Cryptography/OpenPgp/PgpKeyPair.cs:line 22
   at Springburg.Test.PgpCompositionTest.CompressedDataInSignature() in /Users/filipnavara/Projects/springburg/test/PgpCompositionTest.cs:line 19
  Failed NestedSignatures [< 1 ms]
  Error Message:
   System.PlatformNotSupportedException : DSA keys can be imported, but new key generation is not supported on this platform.
  Stack Trace:
     at System.Security.Cryptography.DSA.DSAImplementation.DSASecurityTransforms.GetKeys()
   at System.Security.Cryptography.DSA.DSAImplementation.DSASecurityTransforms.ExportParameters(Boolean includePrivateParameters)
   at Springburg.Cryptography.OpenPgp.PgpPublicKey..ctor(AsymmetricAlgorithm pubKey, DateTime time, Boolean isMasterKey) in /Users/filipnavara/Projects/springburg/src/Cryptography/OpenPgp/PgpPublicKey.cs:line 88
   at Springburg.Cryptography.OpenPgp.PgpKeyPair..ctor(AsymmetricAlgorithm keyPair, DateTime time) in /Users/filipnavara/Projects/springburg/src/Cryptography/OpenPgp/PgpKeyPair.cs:line 22
   at Springburg.Test.PgpCompositionTest.NestedSignatures() in /Users/filipnavara/Projects/springburg/test/PgpCompositionTest.cs:line 44

Failed!  - Failed:    16, Passed:   113, Skipped:     0, Total:   129, Duration: 9 s - /Users/filipnavara/Projects/springburg/test/bin/Debug/net5.0/Springburg.Test.dll (net5.0)
```

**Comment by filipnavara** [comment]
The single ECDsa failing tests seems to be due to lack of support for brainpool curves.
